### ISSUE TITLE
Problem of md5sum  warning when web is refreshed

### ISSUE THREAD

**Issue by dwlee** [RobotWebTools/rosbridge_suite#138]
When web client using roslibjs is refreshed, md5sum warning is occurred. And then the refreshed client can not publish topic for about some second. 

The situation is as below.
1. Launch rosbridge.
`roslaunch rosbridge_server rosbridge_websocket.launch --screen`
2. Load test client 1 html (It is simple html page. it just publishes `/chatter` message which is  `std_msgs/String` type).
3. Load test client 2 html (it only subscribe message sent client 1).
4. Send the string message by /chatter in client 1.
5. Check received message in client 2 side.
6. If you check the received message, and refresh the client 2. The md5sum warning will be happened as below. Try to publish again at client 1, but client 2 can not receive message for a little while .

```
[WARN] [WallTime: 1412842915.168814] Could not process inbound connection: [/rosbridge_websocket] is not a publisher of [/chatter]. Topics are [['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n\n', 'callerid': '/rosbridge_websocket', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/chatter', 'type': 'std_msgs/String'}
```

This is my test code.
https://github.com/robotics-in-concert/rocon_demos/tree/office_concert/office_web_interface/www/web_app/yujin_office/test_app

[test_pub.html](https://github.com/robotics-in-concert/rocon_demos/blob/office_concert/office_web_interface/www/web_app/yujin_office/test_app/test_pub.html) is client 1 and [test_sub.html](https://github.com/robotics-in-concert/rocon_demos/blob/office_concert/office_web_interface/www/web_app/yujin_office/test_app/test_sub.html) is client 2. If push the `chatter`button client 1 publish the simple string included count message.

**Comment by ablakey** [comment]
A workaround I've found is to unadvertise the published topic if possible. My need to publish is infrequent, so I just create the publisher, publish a message, and unadvertise all in that order.  This is ugly but it works.

**Comment by T045T** [comment]
Since several forks have adopted this "quick hack", and it doesn't look like rospy is going to fix the root cause any time soon (assuming it's possible to do so), how about a nicer solution?

I'm thinking a timeout for unregistering topics with no clients, so the publisher survives quick page reloads, but rosbridge doesn't leak publishers. This is particularly important in connection with the service-based tf2_web_republisher, as that will generate new topics for each new client (and as such, for each page reload).

If you think a timeout is an acceptable solution, I'll implement it :)

**Comment by jihoonl** [comment]
Yeah. I think it would be sufficient to keep it in the main stream with some explanation. Thanks @T045T

**Comment by salsalam** [comment]
I'm new to ROS and rosbridge.  I am receiving these warnings and would like to prevent them.  Is it still the case that I should adopt the "quick hack"?  I am running 0.7.13 since I used sudo apt-get install ros-indigo-rosbridge... to install and that's what it gave me.

Thanks for any help you can provide.

**Comment by Sanic** [comment]
I'm interested in that too.
@T045T Did you manage to implement the Timeout yet?

**Comment by jihoonl** [comment]
This should be mitigated by #247

**Comment by jihoonl** [comment]
Otherwise, this is an issue in rospy not in rosbridge.

**Comment by paul-mesnilgrente** [comment]
Hi everyone,

I see that this is an old issue and it seems to be solved. However I have this message:

```text
[WARN] [1511259980.900398]: Could not process inbound connection: [/rosbridge_websocket] is not a publisher of [/ui_action]. Topics are [['/text_to_speech', 'std_msgs/String'], ['/speech_to_text', 'std_msgs/String'], ['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n', 'callerid': '/rosbridge_websocket', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/ui_action', 'type': 'std_msgs/String'}
```

I am using `ros-kinetic` on `Ubuntu 16.04`. Should I apply the quick fix or it has been added to the ubuntu package?

**Comment by gonzalocasas** [comment]
The unregister timeout is really not a sustainable solution. I am using `rosbridge_server` in a context that is not about quick reconnects like the webpage reload case that was mentioned in several of the linked issues, and this really makes it extremely inconvenient to use.

Any hope for a fix for the root cause at some point?
