### ISSUE TITLE
client duplication prevention

### ISSUE THREAD

**Issue by ramezanifar** [RobotWebTools/rosbridge_suite#435]
In my use case, the Internet Explorer Browser that is the client is embedded in an ActiveX Control. 
The problem is whenever one refreshes the embedded browser, as opposed to the stand alone browser, the previous connection is not killed and a new connection is made for the same client.
Now if I look at the /connected_clients topic, I see the IP address is duplicated. For each refresh I get a new connection so after a while I may get many clients that causes serious problems.
So it seems the problem is the Activex control. How can I mitigate this?
As a temporary solution, I read the /connected_clients  topic and if I detect duplication, I reboot the Rosbridge server ( using a supervisory application)  to kill all connections and start fresh.
Obviously all other clients are disturbed for a short time. How can I close a specific connected client?

## Expected Behavior
Ability to to close an existing connected client

## Actual Behavior
Duplicated clients

## Steps to Reproduce the Problem

  1. Use a browser in an ActiveX control
  2. Refresh the browser
  3. check the /connected_clients topic to see duplicated client

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): Melodic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): Ubuntu 18.04
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 0.11.3
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): 17.9.0

**Comment by Axel13fr** [comment]
hi @ramezanifar,

I had a similar issue but in a very different context. A workaround which solved the problem for me: set the "websocket_ping_interval" (2secs for example) and "websocket_ping_timeout" (10secs for example) so that the rosbridge server will disconnect a client who doesn't respond to it. The ping respond is handled on the browser level so the browser has to support this websocket feature.
