### ISSUE TITLE
How to play audio_common message with web audio api?

### ISSUE THREAD

**Issue by BRNKR** [RobotWebTools/rosbridge_suite#576]
Hey,

rosbridge is working like expected. I can subscribe to images and display them like in your tutorials.
i want to send audio from a pc running rosbridge to a web page by using the audio_capture package. i get a wave stream which results as an base64 encoded stream on javascript side.

has anyone an idea how to play the incoming messages with the Web Audio API? i have tried several things but i am not sure if i am doing right.

i look forward to your answers :)

Best regards

**Comment by mvollrath** [comment]
I would make sure you're configuring audio_capture to produce raw `wave` data and understand what all of the parameters for `channels`, `depth`, and `sample_rate` are set to.  Then push these buffers to an appropriate Web Audio API streaming interface, after stripping any base64 **or** use `compression: "cbor"` when you subscribe to the audio topic and it should come in as a byte array instead of base64 string.

This may be an example of similar task on the browser side https://www.npmjs.com/package/websockets-streaming-audio

**Comment by BRNKR** [comment]
Thank you very much for your answer! I was already afraid that no one will be interested.

I am aware of channels and sample_rate. But where do I need the depth information in the web audio api?

The Buffer-lenght of 320 is the length of the bytearray converted from base64. The play function is called on every callback. 

i will have a look into your link. thanks.

**EDIT:**
After decoding the base64 i have a uint8 array with 320 elements. the frequency of the messages is 100 hz. my sample rate is 16000. it should have a frequency of 50hz. is it because of the bit depth of 16bits? then it would make sense. but how do audio_capture fill the message? do i have to take two int8 elements, bitshift one and i will get an 16bit element ?
at the moment i just get noisy sounds from my speakers.


```
// Audio Playback
// --------------
window.AudioContext = window.AudioContext       ||
                              window.webkitAudioContext ||
                              window.mozAudioContext    ||
                              window.oAudioContext      ||
                              window.msAudioContext;
var context = new AudioContext();
var buffer = context.createBuffer(1, 160, 16000);
var nowBuffering = buffer.getChannelData(0);

function fill_buffer(base64) {
  context.resume();
  var binary_string = window.atob(base64);
  var len = binary_string.length;
  var buf = new Float32Array(len);

  var value_int16 = 0;
  var value_first = 0;
  var value_float32 = 0.0;
  for (var i = 0; i < len; i++) {
      var value_int8 = binary_string.charCodeAt(i);
      if(i % 2 == 0){
        value_first = value_int8;
      }
      else{
        value_int16 = value_first && value_int8 << 8;
        value_float32 = value_int16 / 32768.0 - 1;
        if (isNaN(value_float32)){
          value_float32 = 0;
        }
        nowBuffering[i] = value_float32;
      }
  }
  buffer.copyToChannel(buf, 0);
  var source = context.createBufferSource();
  source.buffer = buffer;
  source.connect(context.destination)
  source.start(0)
}

**Comment by jtbandes** [comment]
Closing this issue since it isn't directly related to the rosbridge_suite, and doesn't require action from the maintainers, but is more a general question of how to interpret audio_common msgs and play them with the Web Audio API. If you still need help I'd recommend answers.ros.org or Stack Overflow.
