### ISSUE TITLE
Python undefined names: get_service_uri and node

### ISSUE THREAD

**Issue by cclauss** [RobotWebTools/rosbridge_suite#604]
`get_service_uri` and `node` are _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which has the potential to halt/crash the script on the user.

Related to #593 and #594

$ `flake8 . --select=F821 --show-source`
```
./rosapi/src/rosapi/proxy.py:240:11: F821 undefined name 'get_service_uri'
    uri = get_service_uri(service)
          ^
./rosbridge_server/scripts/rosbridge_websocket.py:304:5: F821 undefined name 'node'
    node.destroy_node()
    ^
```

## Expected Behavior
Functions and variables are defined before they are used.

## Actual Behavior
Functions and variables are not defined before they are used.

## Steps to Reproduce the Problem

1. $ `flake8 . --select=F821 --show-source`

## Specifications

  - ROS Version (`echo $ROS_DISTRO`):
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`):
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`):
  - Tornado Version (`python -c 'import tornado; print tornado.version'`):

**Comment by jtbandes** [comment]
`get_service_uri` occurs in unused code that exists because of an incomplete ROS 2 conversion.

The `node` issue only causes problems when the server is shutting down, which is usually not a clean process anyway (initiated by SIGINT). That's something I'd like to fix though so we can have clean shutdown (would make the tests work more nicely too).
