### ISSUE TITLE
Galactic Release?

### ISSUE THREAD

**Issue by chenjunnn** [RobotWebTools/rosbridge_suite#636]
https://github.com/RobotWebTools/rosbridge_suite/issues/536#issuecomment-898664359 I've found the Foxy version in apt repo, but I still can't find rosbridge_suite for Galactic.

![image](https://user-images.githubusercontent.com/57067221/132096901-a9bad915-0007-4147-ba2d-08dc67b7de55.png)

**Comment by jtbandes** [comment]
We missed the last galactic sync due to a build error I didn’t notice until after the sync (https://github.com/RobotWebTools/rosbridge_suite/commit/ea0b8af80da3ce79c53f1013df6d3b738d625660) So it should be in the next sync. Sorry about that!

You can see the build status at http://repo.ros2.org/status_page/ros_galactic_default.html?q=SYNC
