### ISSUE TITLE
Remove TCP + UDP servers for ROS 2

### ISSUE THREAD

**Issue by jtbandes** [RobotWebTools/rosbridge_suite#639]
The TCP and UDP servers were not ported from ROS 1 to ROS 2. Since they don't work, we might as well remove the unused code to reduce the amount of maintenance required on this repo.

**Comment by GaoGeolone** [comment]
Excuse me, I am still working on TCP server with ros2 on windows 10. And I have an idea, maybe I could start a new project to maintain the tcp part?

**Comment by jtbandes** [comment]
If you have made some changes to get the TCP server working for ROS 2, you are welcome to submit a pull request to this repo with the changes. Ideally you can also add a test like the websocket smoke test: https://github.com/RobotWebTools/rosbridge_suite/blob/ros2/rosbridge_server/test/websocket/smoke.test.py (of course the test will need to be very different to work with TCP)

**Comment by amacneil** [comment]
Out of curiosity, what is your use case is for rosbridge tcp?

I assume everywhere you could use tcp, you would also be able to use websocket instead?

**Comment by GaoGeolone** [comment]
> 
> 
> If you have made some changes to get the TCP server working for ROS 2, you are welcome to submit a pull request to this repo with the changes. Ideally you can also add a test like the websocket smoke test: https://github.com/RobotWebTools/rosbridge_suite/blob/ros2/rosbridge_server/test/websocket/smoke.test.py (of course the test will need to be very different to work with TCP)

@jtbandes Mainly because the problems I came cross while applying rosbridge_suite on Win10, that symlink cannot be taken as an executable ros-node file, so I change the rosbridge_server and rosapi into two pure python packages with their setup.py files. As a consequent, msg and srv have to be moved out of the package with ros-node( rosapi  ). That is to say, the structure of the whole project has changed. It seems diffcult to merge into the current project.
So I upload my version to be [a new branch project](https://github.com/GaoGeolone/ros2bridge_suite) 
Actually, I keep the websocket server as the way it used to serve in rosbridge_suite. Then, I will try to make a tcp-test file as you have suggested.

**Comment by GaoGeolone** [comment]
> 
> 
> Out of curiosity, what is your use case is for rosbridge tcp?
> 
> I assume everywhere you could use tcp, you would also be able to use websocket instead?

Thank you for asking, as shown below, I am trying to communicate with an Unreal Engine Plugin named ROS-Integration ，this plugin of 3rd party defined only a TCP communication channel with Rosbridge( ROS1 version ).  The way to make them work on ROS2, Either adding a websocket channel to that plugin, or polishing the TCP server. As you can see, I choose the latter way

![image](https://user-images.githubusercontent.com/33696048/133533874-9487a4d1-e406-4301-870b-eb0ea8c3a86b.png)

**Comment by jtbandes** [comment]
@GaoGeolone Would you be interested in submitting your patches to this repo? If you have fixed the TCP server, it would be nice to keep that in this repo (rather than a fork) so it's easy for other people to find and use.

**Comment by GaoGeolone** [comment]
> 
> 
> @GaoGeolone Would you be interested in submitting your patches to this repo? If you have fixed the TCP server, it would be nice to keep that in this repo (rather than a fork) so it's easy for other people to find and use.

Fine, I am glad to make contributions to this repo.

**Comment by GaoGeolone** [comment]
But sorry, How can I submit my version to this repo. The relation between these two repos had broken, due to the reconstruction of my project while trying to figure out the way to work on win10.

Maybe U could help me ?
My version of RosBridge[https://github.com/GaoGeolone/ros2bridge_suite](https://github.com/GaoGeolone/ros2bridge_suite)

**Comment by jtbandes** [comment]
The best approach might be to just copy the files into your clone of the rosbridge_suite repo. If the directory structure hasn't changed much, `git diff` should be able to show you where the important changes are.

**Comment by zflat** [comment]
@GaoGeolone Did this recently merged PR change the structure to be compatible with your setup?https://github.com/RobotWebTools/rosbridge_suite/pull/665
