### ISSUE TITLE
PNG compression does nothing

### ISSUE THREAD

**Issue by RalphCodesTheInternet** [RobotWebTools/rosbridge_suite#641]
**PNG compression does nothing**

- Version: 1.0.8 
- Platform: Ubuntu 20.04

**Steps To Reproduce**
Subscribe to a topic with and without compression:
`
var listener = new ROSLIB.Topic({
    ros: ros,
    name: '/camera/color/image_raw',
    messageType: 'sensor_msgs/Image',
    compression: 'none'
});

var listener = new ROSLIB.Topic({
    ros: ros,
    name: '/camera/color/image_raw',
    messageType: 'sensor_msgs/Image',
    compression: 'png'
});
`

**Expected Behavior**
The data in the message should be different and of different size

**Actual Behavior**
Nothing has changed. Looks like only cbor / cbor-raw is working

https://github.com/RobotWebTools/rosbridge_suite/blob/0a1a947e96a41c3a974f2985f5dfbc02a232b1c9/rosbridge_library/src/rosbridge_library/capabilities/subscribe.py#L107

**Comment by mvollrath** [comment]
How do are you checking the output?  If you're going through ROSLIB it is decompressing before it gets to the subscribe callback.  CBOR would appear different because it has different output for typed arrays.  Check your browser's network sniffer to see what is coming in on the wire, and check the profiler to see performance differences.

FWIW png should be deprecated and removed, it is superseded by WebSocket per-message-deflate which is enabled by default and supported by most browsers and clients.  And if you are using ROSLIB you should be using CBOR for `sensor_msgs/Image`.
