### ISSUE TITLE
rosbridge_server bug with NAT ports mapping

### ISSUE THREAD

**Issue by rscova** [RobotWebTools/rosbridge_suite#762]
**Description**
When you start the server in your IP address and you want to access the topics through your router's IP public address you need to map the ports (I did that using NAT). But the only way that this work is when you map the ports to match, I meant:
Ports: 9090 -> 45666 (Bad behaviour, rosbridge_server doesn't recognize the connection)
Ports: 45666 -> 45666 (Good behaviour, rosbridge_server recognizes the connection)

This is because even if you use NAT to remap the port, the client sends an HTTP `header Host: publicip:45666` which rosbridge_server complains about.

My recommendation, at least, if you don't want to fix this bug, would be to add this info in the documentation.

- Library Version: ros2 branch
- ROS Version: Galactic
- Platform / OS: Ubuntu 20.04

**Steps To Reproduce**

`ros2 launch rosbridge_server rosbridge_websocket_launch.xml address:=192.168.1.x port:=9090`

NAT remapping Ports 9090 to X (the one your router allows you)

Try to connect with WebSockets with Foxglove, or your own application using your router's public IP and the port remapped.

**Expected Behavior**
You can connect with rosbridge_server

**Actual Behavior**
You **can't** connect with rosbridge_server

**Comment by rubenanapu** [comment]
On ros (ros1), there was a similar problem when running rosbridge inside a docker container in which the port of the host was different from the port of the docker container.

In that case, it was enough to pass the **_websocket_external_port_** parameter, as explained in the link below.

https://github.com/RobotWebTools/rosbridge_suite/issues/529#issuecomment-713857597

However, for ROS2, the code in this repo does not have that parameter.

I know this is not a solution, but I'm telling you because this may give you some ideas.
