### ISSUE TITLE
How should I parse the received point cloud data transmitted by rosbridge on the web side?

### ISSUE THREAD

**Issue by SenHe524** [RobotWebTools/rosbridge_suite#851]
**Description**

I tried to use js on the web side to obtain the data transmitted by rosbridge. When I tried to get point cloud (sensor_msgs/msg/PointCloud2) data from the web side, I couldn't find a proper way to solve the data field in (sensor_msgs/msg/PointCloud2) data on the web side, could you please provide a routine?

**Comment by SenHe524** [comment]
@ @jtbandes @RainCT @baalexander @defunctzombie

**Comment by defunctzombie** [comment]
Please be mindful when opening a bug issue that it is for broken functionality rather than a question. If a feature is not working please describe what is not working including the errors you are seeing, what you have tried that has worked, and include more details and sample code to help diagnose what it is you are trying to do.

More generally I'd recommend directing your questions to https://answers.ros.org/questions/ to get more visibility from others.
